language: python
python:
  - "3.7-dev"
install:
  - cp contrib/env-sample .env
  - pip install -r requirements-dev.txt codecov
script:
  - flake8 .
  - pycodestyle .
  - python -m doctest README.md pybling/notas.py -v
  - pytest tests/tests.py --verbosity=1 --cov=pybling
after_success:
  - codecov